[pkp-lib] #6999 Fixing directSalesPrice fixes OpenAccess selection for SubmissionFile
pkp/omp pull request #1106
Opened 2022-04-18 15:12 UTC by defstat

2022-04-19 16:22 UTC, asmecher requested changes
One item needing clarification, thanks!

2022-04-19 18:44 UTC, defstat commented on plugins/importexport/native/filter/NativeXmlChapterFilter.inc.php
> +        Repo::author()->addToChapter($authorId, $chapter->getId(), false, $seq);
Right now it seems that there is no way to define Primary Contact for a ChapterAuthor within the UI. Also, when creating the Author entity, it seems that this attribute has not been taken into account. There is a primaryContact attribute in both submission_chapters and submission_chapter_authors though. Is there a purpose behind that?

2022-04-21 21:54 UTC, asmecher commented on plugins/importexport/native/filter/NativeXmlChapterFilter.inc.php
> +        Repo::author()->addToChapter($authorId, $chapter->getId(), false, $seq);
Can you check if that's a regression from the `stable-3_3_0` branch or if it's a long-standing forgotten feature?

2022-05-03 14:52 UTC, defstat commented on plugins/importexport/native/filter/NativeXmlChapterFilter.inc.php
> +        Repo::author()->addToChapter($authorId, $chapter->getId(), false, $seq);
[This](https://github.com/pkp/omp/blob/3bb7da02701eea030a77e55aea6408f2c9e4ab70/controllers/grid/users/chapter/ChapterGridHandler.inc.php#L309) is a line of code from stable-3_2_1. It seems that OMP never used `primary_contact` column - It uses `seq` column though (both interface and code/db). The user interface of stable_3_3_0 does not allow the user to declare/change the `seq` of the ChapterAuthor anymore.

2022-05-03 22:41 UTC, asmecher commented on plugins/importexport/native/filter/NativeXmlChapterFilter.inc.php
> +        Repo::author()->addToChapter($authorId, $chapter->getId(), false, $seq);
OK, I'm satisfied that this isn't a regression, thanks!

2022-05-03 22:42 UTC, merged