pkp/pkp-lib#10511 fix and cleanup invalid series navigation menu items
pkp/omp pull request #1772
Opened 2024-11-22 16:13 UTC by kaitlinnewson

2024-11-25 11:39 UTC, jonasraoni requested changes
Hi @kaitlinnewson! I just requested one update.

2024-11-25 12:25 UTC, jonasraoni commented
Ah, I've spotted another problem...

The offending menu item can be the parent of other menu items, so if you remove it, the dependent items will be gone as well... In fact not, because a foreign key was forgotten (I'll create/update another issue to cover it), anyway, it needs to be addressed 🙃

So again, we have two options:
- Removing such item should cause its children to take its place on the tree.
- We setup the `path` with `null` and "convert" such items to a placeholder (it doesn't exist, so the closest to it would be a URL item pointing perhaps to `./`).

2024-11-25 12:38 UTC, jonasraoni commented
FYI the current behavior is to hide everything which is under an orphan menu item, which I don't think it's ideal 🤔

2024-11-25 19:31 UTC, kaitlinnewson commented on classes/migration/upgrade/v3_5_0/I10511_RemoveSeriesMenuItems.php
> +            ->where('path', '�*�escapeWhenCastingToString')
Reviewing this again - @jonasraoni do you mean to do a join, and then remove all entries that do not belong to an existing series?

2024-11-25 19:43 UTC, jonasraoni commented on classes/migration/upgrade/v3_5_0/I10511_RemoveSeriesMenuItems.php
> +            ->where('path', '�*�escapeWhenCastingToString')
Yep, there's just an extra detail that I wrote below https://github.com/pkp/omp/pull/1772#issuecomment-2497880502 :)

2024-11-25 21:07 UTC, kaitlinnewson commented
@jonasraoni PR has been updated and ready for another look. I noticed there is only one level of nesting in the menus, so I opted to set the parent to `null` instead, which keeps it assigned in the navigation menu. Alternatively we could delete it from `navigation_menu_item_assignments` and then it would still exist but just not be assigned to the menu.

2024-11-29 19:20 UTC, jonasraoni approved these changes
It would be better to do both operations without materializing the IDs, but even on a large multi-journal installation it's unlikely that we'll have many defective items 🙃

2024-11-29 19:20 UTC, jonasraoni commented on classes/migration/upgrade/v3_5_0/I10511_RemoveSeriesMenuItems.php
> +            ->update(['parent_id' => null]);
```suggestion
        if (!$invalidNavigationMenuItemIds->count()) {
            return;
        }

        DB::table('navigation_menu_item_assignments')
            ->whereIn('parent_id', $invalidNavigationMenuItemIds)
            ->update(['parent_id' => null]);
```

2024-11-29 21:53 UTC, merged